
name: Copy demo file

on:
  push:
    branches: [ master ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: rsync lab
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: src/index.js
          remote_path: /var/www/html/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: 22
          remote_user: deployer
          remote_key: "${{ secrets.DEPLOY_KEY }}"
   
